@startmindmap
title Market Mind Map
* Competitor and Market Trends
** Competitor Sites
*** https://www.learningmachine.com/
*** https://www.accredible.com/
*** https://www.parchment.com
*** https://info.credly.com/ 
** Inspiration Sites
*** https://www.scholarme.co
*** https://www.securiti.ai/
*** https://monday.com/

left side
** Industry Sites
*** https://www.uport.me/
*** https://sovrin.org/
*** https://identity.foundation/
*** https://credentialengine.org/

** Market Trends/Design Language
*** https://ant.design/
@endmindmap

